services:
  devcontainer:
    build:
      context: ../..
      dockerfile: .claude/claudecontainer/Dockerfile
      args:
        TZ: "${TZ:-Europe/Stockholm}"
    user: node
    command: sleep infinity
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
    volumes:
      # user home .claude directory (includes .claude.json)
      - ../../claudecontainer-user-dot-claude:/home/node/.claude
      - ../../claudecontainer-user-dot-claude/.claude.json:/home/node/.claude.json
      # Project workspace mount
      - ../..:/workspace
      # git worktree mount for monorepo
      - ../../../master/.git:/master/.git
    working_dir: /workspace
    profiles:
      - devcontainer

  claude:
    extends:
      service: devcontainer
    env_file:
      - ~/.env.claudecontainer
    stdin_open: true
    tty: true
    entrypoint: claude
    profiles: !reset []
